// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC8yAiH7NfR15ZgrJmceNHMRpxTP1tUe04',
    appId: '1:828805649050:web:7ad7ddb4293a35541b4523',
    messagingSenderId: '828805649050',
    projectId: 'b612-900dd',
    authDomain: 'b612-900dd.firebaseapp.com',
    storageBucket: 'b612-900dd.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDFBDilyxXVTP1dVQUuXEGC0L9QcVRimEQ',
    appId: '1:828805649050:android:3693e51c0b01accd1b4523',
    messagingSenderId: '828805649050',
    projectId: 'b612-900dd',
    storageBucket: 'b612-900dd.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDWI_NKiVBoyIRhIEzkSWXLgHiz49yl6S0',
    appId: '1:828805649050:ios:22b11618f995be0e1b4523',
    messagingSenderId: '828805649050',
    projectId: 'b612-900dd',
    storageBucket: 'b612-900dd.firebasestorage.app',
    androidClientId: '828805649050-9ttgkihu4u77t6ia8t09tjnjjket5ltt.apps.googleusercontent.com',
    iosClientId: '828805649050-ju4vltq98fov99ah67kafsnjqn5nbjcj.apps.googleusercontent.com',
    iosBundleId: 'com.example.b6121',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDWI_NKiVBoyIRhIEzkSWXLgHiz49yl6S0',
    appId: '1:828805649050:ios:22b11618f995be0e1b4523',
    messagingSenderId: '828805649050',
    projectId: 'b612-900dd',
    storageBucket: 'b612-900dd.firebasestorage.app',
    androidClientId: '828805649050-9ttgkihu4u77t6ia8t09tjnjjket5ltt.apps.googleusercontent.com',
    iosClientId: '828805649050-ju4vltq98fov99ah67kafsnjqn5nbjcj.apps.googleusercontent.com',
    iosBundleId: 'com.example.b6121',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC8yAiH7NfR15ZgrJmceNHMRpxTP1tUe04',
    appId: '1:828805649050:web:93cb0290db18a01c1b4523',
    messagingSenderId: '828805649050',
    projectId: 'b612-900dd',
    authDomain: 'b612-900dd.firebaseapp.com',
    storageBucket: 'b612-900dd.firebasestorage.app',
  );
}
